train_file: 'data_simmc/preprocess/simmc_train.txt'
val_file: 'data_simmc/preprocess/simmc_dev.txt'                
test_file: 'data_simmc/preprocess/simmc_devtest.txt'

#image_root: 'data_image/SIMMC/images/'
image_root: '1234/data_image/1234'

image_res: 384
batch_size_train: 8
batch_size_test:  8

alpha: 0.4
distill: True
warm_up: False

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.00}
schedular: {sched: cosine, lr: 2e-5, epochs: 20, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







